---
- name: Preparing restore strategy
  hosts: localhost
  become: true
  gather_facts: false
  vars_files:
    - varsrestore.yaml
  tasks:
    - name: create the namespace "{{ nsrestore }}"
      k8s:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: Namespace
        name: "{{ nsrestore }}"
        state: present

    - name: Copy the secret yaml file
      copy:
        src: files/secret.yaml
        dest: /tmp/secret.yaml

    - name: Ensure the secret is created
      k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        namespace: "{{ nsrestore }}"
        src: /tmp/secret.yaml

    - name: Copy target yaml file
      copy:
        src: files/target.yaml
        dest: /tmp/target.yaml

    - name: Ensure target is available in "{{ nsrestore }}"
      k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        namespace: "{{ nsrestore }}"
        src: /tmp/target.yaml
